#!/usr/bin/env bash
  #========================================
  # Project: LIBAACS INSTALLER v2.4
  # Author:  ConzZah / ©️ 2025
  # Last Modification: 05.03.2025 / 18:06
  #========================================
main () {
doso="sudo"
done_msg="[ DONE INSTALLING LIBAACS ]"
mkdir -p "$HOME/.config/aacs/"; cd "$HOME/.config/aacs/"
_debian="vlc libaacs0 libbluray-bdj libbluray2 curl 7zip"
_alpine="vlc-qt libaacs libbluray curl 7zip base64"
echo "[ ConzZah's LIBAACS INSTALLER v2.4 ]"
echo -e "\n[ PRESS ANY KEY TO START ]\n"; read -n 1 -s
_install ;}

_install () {
# package manager detection
for pkg in apk apt; do type -p $pkg >/dev/null && break; done
if [[ "$pkg" == "apk" ]]; then pkg="apk add"; install="$_alpine"; doso="doas"; fi
if [[ "$pkg" == "apt" ]]; then pkg="apt install"; install="$_debian"; fi
# check 4 missing packages
echo -e "[ CHECKING FOR MISSING PACKAGES ... ]\n"
! type -p dpkg >/dev/null && $doso $pkg dpkg -y
for dep in $install; do dep_status="$(dpkg -l "$dep" 2>/dev/null| tail -n1| cut -c -2)"
if [[ "$dep_status" =~ ^("un"|"")$ ]] && ! type -p $dep >/dev/null; then
echo "MISSING: $dep"; missing="$dep $missing"; fi 
done
[ -n "$missing" ] && $doso $pkg $missing && echo -e "\n$done_msg\n"
keydb_updatecheck ;}

keydb_updatecheck () {
# checks if there's been an update to keydb.cfg by comparing two files 
touch .last_updated; echo -e "[ CHECKING FOR UPDATED KEYDB.CFG ... ]\n"
curl -sLo "last_updated" "https://gist.github.com/ConzZah/57d1fecd5cba6cb49e45f4ff3149128c/raw"
gist_link="$(sed -n '2p' last_updated)"; sed -i '2d' last_updated
echo -e "[ LOCAL KEYDB:  $(cut -c  20- .last_updated) ]\n"
echo -e "[ REMOTE KEYDB: $(cut -c  20- last_updated) ]\n"
diff -q last_updated .last_updated >/dev/null 2>&1 && { echo -e "[ KEYDB.CFG UP TO DATE ]\n"; rm last_updated; quit ;} || keydb_downloader ;}

keydb_downloader () {
# keydb.cfg download function
echo -e "[ DOWNLOADING KEYDB.CFG ... ]\n"
curl -# -L -o "keydb_eng.7z.txt.zip" "$gist_link"
echo -e "\n[ EXTRACTING KEYDB.CFG ... ]\n"
7z e keydb_eng.7z.txt.zip keydb_eng.7z.txt -r >/dev/null 2>&1
base64 -d keydb_eng.7z.txt > keydb_eng.7z
7z x keydb_eng.7z >/dev/null 2>&1
mv keydb.cfg KEYDB.cfg; rm -f keydb_eng.7z*
mv -f last_updated .last_updated; quit ;}

quit () { echo -e "[ DONE. ENJOY YOUR BLU-RAYS! ] \n\n[ PRESS ANY KEY TO EXIT ]\n"; read -n 1 -s; exit ;}

main
